food/urls.py
from django.conf.urls import url
from .views import index,add_meal,delete_meal,update_meal,view_meal, login

urlpatterns = [
	url(r'^$', login, name='login'),
	url(r'^index$', index, name='index'),
	# url(r'^$', index, name='index'),
	url(r'^add_meal$', add_meal, name='add-meal'),
	url(r'^delete_meal/(?P<meal_id>\d+)$', delete_meal, name='delete-meal'),
	url(r'^update_meal/(?P<meal_id>\d+)$', update_meal, name='update-meal'),
	url(r'^view_meal/(?P<meal_id>\d+)$', view_meal, name='view-meal'),
]

food_tracker/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include(('food.urls', 'food'), namespace="food")),
    url(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='login.html'), name='auth_login'),
    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(next_page='food:login'), name='auth_logout'),
    url(r'^accounts/password/change$', auth_views.PasswordChangeView.as_view(template_name='password_change.html',success_url=reverse_lazy('food:login')),name='auth_password_change'),

]

food/models.py
from django.db import models

# Create your models here.
class Food(models.Model):
	
	name = models.CharField(verbose_name="Food Name", max_length=200)
	calories = models.FloatField(verbose_name="Calories (kcal)")
	total_fat = models.FloatField(verbose_name="Total Fat (g)")
	saturated_fat = models.FloatField(verbose_name="Saturated Fat (g)")
	cholesterol = models.FloatField(verbose_name="Cholesterol (mg)", default = 0.00)
	sodium = models.FloatField(verbose_name="Sodium (mg)", default = 0.00)
	total_carbohydrate = models.FloatField(verbose_name="Total Carbohydrate (g)", default = 0.00)
	dietary_fibre = models.FloatField(verbose_name="Dietary Fibre (g)", default = 0.00)
	sugar = models.FloatField(verbose_name="Sugar (g)", default = 0.00)
	protein = models.FloatField(verbose_name="Protein (g)", default = 0.00)


	def __str__(self):
		return "%s" % self.name


class Meal(models.Model):

	BREAKFAST = 1
	MORNING_SNACK = 2
	LUNCH = 3
	AFTERNOON_SNACK = 4
	DINNER = 5
	EVENING_SNACK = 6

	MEAL_TIME_TYPES = (
		(BREAKFAST, "Breakfast"),
		(MORNING_SNACK, "Morning Snack"),
		(LUNCH, "Lunch"),
		(AFTERNOON_SNACK, "Afternoon Snack"),
		(DINNER, "Dinner"),
		(EVENING_SNACK, "Evening Snack")

	)
	food = models.ForeignKey(Food, verbose_name="Food",on_delete = models.CASCADE)
	serving_size = models.IntegerField(verbose_name="Serving Size")
	meal_time = models.IntegerField(verbose_name="Meal Time", choices=MEAL_TIME_TYPES)

	def get_total_calories(self):
		return self.serving_size*self.food.calories

	def get_total_fat(self):
		return self.serving_size*self.food.total_fat

	def get_total_saturated_fat(self):
		return self.serving_size*self.food.saturated_fat

	def get_total_cholesterol(self):
		return self.serving_size*self.food.cholesterol

	def get_total_sodium(self):
		return self.serving_size*self.food.sodium

	def get_total_carbohydrate(self):
		return self.serving_size*self.food.total_carbohydrate

	def get_total_dietary_fiber(self):
		return self.serving_size*self.food.dietary_fibre

	def get_total_sugar(self):
		return self.serving_size*self.food.sugar

	def get_total_protein(self):
		return self.serving_size*self.food.protein	

food/forms.py
from django import forms
from .models import Meal

class MealForm(forms.ModelForm):
	class Meta:
		model = Meal
		fields = "__all__"

food/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from .models import Meal
from .forms import MealForm

# Create your views here.
def index(request):
	if request.user.is_authenticated:
		# return HttpResponse("Hello, world. You're at the index page.")
		template = 'list.html'
		meals = Meal.objects.all()
		context = {
			'meals': meals,
		}
		return render(request, template, context)
	else:
		return HttpResponseRedirect(reverse_lazy('auth_login'))


def add_meal(request):
	if request.user.is_authenticated:
		template = "add_meal.html"
		
		if request.method == "POST":
			form = MealForm(request.POST)
			if form.is_valid():
				form.save()
			return HttpResponseRedirect(reverse_lazy('food:index'))

		else:
			context = {
				'meal_form': MealForm(),
			}
			return render(request, template, context)
	else:
		return HttpResponseRedirect(reverse_lazy('auth_login'))


def delete_meal(request, meal_id):
	if request.user.is_authenticated:
		meal = Meal.objects.get(id=int(meal_id))
		meal.delete()
		return HttpResponseRedirect(reverse_lazy('food:index'))
	else:
		return HttpResponseRedirect(reverse_lazy('auth_login'))



def update_meal(request, meal_id):
	if request.user.is_authenticated:
		template = "update_meal.html"
		meal = Meal.objects.get(id=int(meal_id))

		if request.method == "POST":
			form = MealForm(request.POST, instance=meal)
			if form.is_valid():
				form.save()
			return HttpResponseRedirect(reverse_lazy('food:index'))
		else:
			context = {
				'meal_form': MealForm(instance=meal),
			}
			return render(request, template, context)
	else:
		return HttpResponseRedirect(reverse_lazy('auth_login'))



def view_meal(request, meal_id):
	if request.user.is_authenticated:
		template = "view_meal.html"
		meal = Meal.objects.get(id=int(meal_id))

		context = {
			'meal': meal,
		}
		return render(request, template, context)
	else:
		return HttpResponseRedirect(reverse_lazy('auth_login'))


def login(request):
	if request.user.is_authenticated:
		return HttpResponseRedirect(reverse_lazy('food:index'))
	else:
		return HttpResponseRedirect(reverse_lazy('auth_login'))

templates/add_meal.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>
	<body>
		<div class="container mt-5">
		<div class="row justify-content-md-center">
			<div>
		<h1>My Food Tracker - Add Meal</h1>
		<form role="form" action="" method="POST">
		    {% csrf_token %}
			<table class="table table-bordered table-striped">
				<tbody>
					<tr>
						<th>Food</th>
						<th>{{ meal_form.food }}</th>
					</tr>
					<tr>
						<th>Serving Size</th>
						<th>{{ meal_form.serving_size }}</th>
					</tr>
					<tr>
						<th>Meal Time</th>
						<th>{{ meal_form.meal_time }}</th>
					</tr>
				</tbody>
			</table>
			<button type="submit" class="btn btn-success">Save</button>
		</form>
		</div>
		</div>
	</div>	
	</body>
</html>

templates/list.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
	</head>
	<body>
		<div class="container mt-5">
		<div class="row justify-content-md-center">
			<div>
		<h1>My Food Tracker</h1> <br /><br />

		<a href="{% url 'auth_logout' %}" class="btn btn-success">Logout</a> <br /><br />

		<a href="{% url 'auth_password_change' %}" class="btn btn-success">Change Password</a> <br /><br />

		<a href="{% url 'food:add-meal' %}" class="btn btn-success">Add Meal</a> <br /><br />

		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th>Food</th>
					<th>Meal Time</th>
					<th>Total Calories</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				{% for meal in meals %}
				<tr>
					<td>{{ meal.food.name }}</td>
					<td>{{ meal.get_meal_time_display }}</td>
					<td>{{ meal.get_total_calories }} kcal</td>
					<td>
						<a href="{% url 'food:view-meal' meal.id %}" class="btn btn-info">View</a>
					</td>
					<td>
						<a href="{% url 'food:update-meal' meal.id %}" class="btn btn-primary">Update</a>
					</td>
					<td>
						<a href="{% url 'food:delete-meal' meal.id %}" class="btn btn-danger">Delete</a>
					</td>
				</tr>
				{% empty %}
				<tr>
					<td colspan=6>No meals yet</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		</div>
		</div>
	</div>		
	</body>
</html>

templates/login.html
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

        <style type="text/css">
            html,
            body {
                height: 100%;
            }

            body {
                padding-top: 40px;
                padding-bottom: 40px;
            }

            .form-signin {
                width: 100%;
                max-width: 330px;
                padding: 15px;
                margin: auto;
            }
        </style>

    </head>

    <body class="text-center">
        {{ form.errors }}
        <form class="form-signin" method="POST" action="{% url 'auth_login' %}" role="form">
            {% csrf_token %}

            <h1>My Food Tracker</h1>

            {{ form.username.label }}
            {{ form.username }}
            <br>
            {{ form.password.label }}
            {{ form.password }}

            <button class="btn btn-lg btn-primary" type="submit">Sign in</button>
            <input type="hidden" name="next" value="{% url 'food:index' %}" />
        </form>
    </body>
</html>

templates/password_change.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>
	<body>
		<h1>My Food Tracker</h1>
		<a href="{% url 'auth_logout' %}">Logout</a> <br /><br />

		{{ form.errors }}

		<form method="POST" action="{% url 'auth_password_change' %}">
		    {% csrf_token %}

		    {{ form.old_password.label }}
		    {{ form.old_password }} <br /><br />

		    {{ form.new_password1.label }}
		    {{ form.new_password1 }} <br /><br />
		    
		    {{ form.new_password2.label }}
		    {{ form.new_password2 }} <br /><br />

		    <button type="submit" class="btn btn-success">Change password</button>
		</form>
	</body>
</html>

templates/update_meal.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>
	<body>
		<h1>My Food Tracker - Update Meal</h1>
		<form role="form" action="" method="POST">
		    {% csrf_token %}
			<table class="table table-bordered table-striped">
				<tbody>
					<tr>
						<th>Food</th>
						<th>{{ meal_form.food }}</th>
					</tr>
					<tr>
						<th>Serving Size</th>
						<th>{{ meal_form.serving_size }}</th>
					</tr>
					<tr>
						<th>Meal Time</th>
						<th>{{ meal_form.meal_time }}</th>
					</tr>
				</tbody>
			</table>
			<button type="submit" class="btn btn-success">Save</button>
		</form>
	</body>
</html>

templates/view_meal.html
<html>
<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
</head>
<body>
	<div class="container mt-5">
		<div class="row justify-content-md-center">
			<div>
			<h1 class="mb-4">My Food Tracker - View Meal Details</h1>
			<h3 class=""><b>{{ meal.food.name }}</b></h3>
			
			<table class="table table-bordered table-striped col col-5" >
				<tbody>
					<tr>
						<th>Calories (kcal)</th>
						<th>{{ meal.get_total_calories }}</th>
					</tr>
					<tr>
						<th>Serving Size</th>
						<th>{{ meal.serving_size }}</th>
					</tr>
					<tr>
						<th>Total Fat (g)</th>
						<th>{{ meal.get_total_fat }}</th>
					</tr>
					<tr>
						<th>Saturated Fat (g)</th>
						<th>{{ meal.get_total_saturated_fat }}</th>
					</tr>
					<tr>
						<th>Cholesterol (mg)</th>
						<th>{{ meal.get_total_cholesterol }}</th>
					</tr>
					<tr>
						<th>Sodium (mg)</th>
						<th>{{ meal.get_total_sodium }}</th>
					</tr>
					<tr>
						<th>Total Carbohydrates (g)</th>
						<th>{{ meal.get_total_carbohydrate }}</th>
					</tr>
					<tr>
						<th>Dietary Fiber (g)</th>
						<th>{{ meal.get_total_dietary_fiber }}</th>
					</tr>
					<tr>
						<th>Sugar (g)</th>
						<th>{{ meal.get_total_sugar }}</th>
					</tr>
					<tr>
						<th>Protein (g)</th>
						<th>{{ meal.get_total_protein }}</th>
					</tr>
				</tbody>
			</table>
			</div>
		</div>
	</div>		
	
	</body>
</html>